### ISSUE TITLE
There is no certificate created yet

### ISSUE THREAD

**Issue by rv-vsilva** [newrelic/nr1-cloud-optimize#11]
Hey guys, we tried to run `nr1 nerdpack:serve` but we got this error

```
There is no certificate created yet.
Error: An error ocurred while performing the operation
    at CallocService._buildRequest (/usr/local/lib/newrelic-cli/node_modules/@datanerd/3pp-cli-utils/src/ServiceFacade.js:149:23)
```

But I didn't find anything related, could you help us to fix this?

Thanks

**Comment by Kav91** [comment]
@rv-vsilva have you created a profile first? this is not a cloud-optimize specific error, but something to do with the cli configuration.

**Comment by rv-vsilva** [comment]
Thanks! Yes... I'm trying to validate if the provided key is working. I will close the issue as this is not related.
