### ISSUE TITLE
Main Page - Get Started Guide

### ISSUE THREAD

**Issue by aso1124** [newrelic/nr1-cloud-optimize#116]
This task encapsulates the work required to update the Get Started Guide, identified as part of the [Cloud Optimize UI Refresh](https://github.com/orgs/newrelic/projects/70/views/1) project. 

Please see the project README for more details on this initiative.

**Comment by Kav91** [comment]
@aso1124 test link: https://onenr.io/0LwG6gdYpQ6

**Comment by aso1124** [comment]
@Kav91 couple notes:
- App should open by default in "beta" view
- App should revert to my last choice - when I switch to Beta, close and then reopen the app, I am back in Stable

**Comment by aso1124** [comment]
@Kav91 - I think the wording helps (what do you think?), but is a bit dense .. 

Updating to include a few line breaks in the text above, to help with readability (there should be space separating them, not just a new line break, basically as below). Also, there was a typo in the "Create a workload" text, so can you update with the text below for that also?

1. Create a workload (optional)

Cloud Optimize uses Workloads to analyze specific sets of entities. Workloads allow you to group related entities, using logical categories such as cloud region, business capability, or business owner. 

If the grouping of entities that you need does not yet exist, click "Create a workload" now. If the the Workloads you need have already been created, move on to the next step.

2. Create a collection

While Workloads are used to efficiently target logically related groups of entities, a Cloud Optimize collection allows you to assemble one or more Workloads together for analysis. 

Click on "Create collection" to select the Workloads you need to include. If the Workload you need isn't listed, return to the previous step to create it.

3. Analyze the collection

Your collection should now show up in the collections table. At the end of the row for your collection, click on the '...' to see the set of available actions. 

Run an analysis by selecting either the "Run (analyze past 7 days)" or "Run with time range" options. 

If your collection contains a large workload, the analysis may take some time to process.

4. View the Results

Once the analysis is complete, a "Results" option will now be available as an action for your collection (click on '...' in the table row). 

Select "Results" to see the optimization and cost analysis generated for your collection! 

If you need to change the settings used in the analysis, use the "Edit Optimization Config" or "Edit Suggestions Config" actions for your collection.

**Comment by aso1124** [comment]
@Kav91 I think this is still work in progress, but some other thoughts:
- Change the "Dismiss" button to "Close" -> this is to temporarily close the quick start
- Beside (under?) the "Close" button, add a checkbox with "Don't show me this guide again" -> this is to permanently dismiss the guide
- add spacing to separate the panel from the main listing section
- the content for the quick start should be positioned in the middle of the panel (it is now positioned toward the bottom)
