### ISSUE TITLE
Demonstrate projected utilization for suggested changes to gauge risk of change

### ISSUE THREAD

**Issue by bl25322** [newrelic/nr1-cloud-optimize#13]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

While showing this off, a key stakeholder asked "whatever it recommends it should not put him at risk of under deployment".

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

Could we include what the estimated cpu/memory load would be if an instance is right-sized to a suggested system.

Could we show (for an instance)...  timeseries of utilization over xx period of time, and projected utilization over that same period of time if a suggested instance is put in place.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )
It is great it points on where you can save money but it does not give a gauge of the risk of underdeployment if a change is made.

**Comment by tangollama** [comment]
@Kav91 what do you think about this issue? Is it valid to remain on the list?

**Comment by Kav91** [comment]
@tangollama I think we should close it. 
This would be valuable, but I can't think of a generic/simple way to handle it which would also be somewhat reliable/valuable. 
Eg. even with trying to do charts to show projected values, say with a different instance type, CPU architecture, threads, burst/non-burstable options are things that could change, which is hard to project.
