### ISSUE TITLE
Results and jobs missing 

### ISSUE THREAD

**Issue by vc102961** [newrelic/nr1-cloud-optimize#130]
I installed the app on a customer account.  After the workloads and collection definition I try to Run (Analyze past 7 days) and Run with time range (got the requesting job confirmation) but nothing happens. No results is available and the Job History is empty.
How can I investigate the issue ? Thanks

**Comment by dzadonskii** [comment]
Try to create a new User API key with the name "NR1-OPTIMIZER-KEY" in the same account where you run the Job. Fixed for me.

**Comment by Kav91** [comment]
Related to  #114, closing to track under that issue.

**Comment by PolovicJ** [comment]
> Try to create a new User API key with the name "NR1-OPTIMIZER-KEY" in the same account where you run the Job. Fixed for me.

I'm not sure if I overlooked this requirement in the documentation or it's really missing there. Very useful hint! Thanks @dzadonskii
