### ISSUE TITLE
Separate ec2 on-demand vs spot

### ISSUE THREAD

**Issue by jfdoube** [newrelic/nr1-cloud-optimize#18]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
Currently the cloud optimize can provide optimization insight on ec2 regardless or their type.
It would be nice to get valid optimization based on ec2 type (spot/on-demand) since they don't cost the same and spots are already cost optimized

[NOTE]: # ( Provide a brief overview of what the new feature is all about. )

## Desired Behaviour

[NOTE]: # ( Tell us how the new feature should work. Be specific. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Kav91** [comment]
@jfdoube thanks for raising this, we have actually been discussing this internally and with some customers also.

Spots can still be optimized as we have seen customers using oversized ones, so this nerdpack can still provide some level of guidance. 

However to your point on cost, we need a flag / attribute to tell us this instance is a spot instance somehow. As soon as we have that it is simple enough to line up the appropriate spot pricing and optimization suggestion if needed.

**Comment by Kav91** [comment]
If spot is detected, spot pricing is now used. 
Please feel free to re-open or create another issue if the UX needs to be improved to better visual this.
