### ISSUE TITLE
Update copy to New Relic style guidelines

### ISSUE THREAD

**Issue by tobyminton** [newrelic/nr1-cloud-optimize#19]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary

This request has a markup from New Relic's UI writer with copy changes to match New Relic's UI style guidelines and improve readability and usability.
## Desired Behaviour

Markup document (internal access only): https://docs.google.com/document/d/10dWqR0vPF6q0r9UYhziW4xyHWdlVlZYBrUAX-KMG0a4/edit?usp=sharing

## Possible Solution

Apply changes per the markup above.

## Additional context

We need to make sure all the New Relic One applications we create and share publicly match our style guidelines and are as easy to understand and use as possible.

**Comment by Kav91** [comment]
Large refactor has taken place, closing this issue.
