### ISSUE TITLE
Add Entity column to Optimization Candidate view

### ISSUE THREAD

**Issue by StephenGoodall** [newrelic/nr1-cloud-optimize#20]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
I'd like to add the Entity Name to the Optimization Candidate view. 

## Desired Behaviour

Display an extra column next to hostname to show the entity name - as these are more meaningful than the private IP based names that AWS use by default.

## Possible Solution

I have added a new column to the optimizationCandidate.js file and added the column to the NRQL query in utils.js and this seems to work:
![image](https://user-images.githubusercontent.com/5859975/71606271-995f5400-2bc3-11ea-9420-5d57dbdb8297.png)

## Additional context

We use the display_name value in our newrelic-infra.yml as we use schedules to spin instances up and would prefer to see what "group" of ec2 server it was, eg. is it one of our web servers, or an app server (they run different groups of apps).

After adding that config, the value is stored as entityName so I'd like to be able to see it on the page.

The link that it takes you too is the same as hostname, it's just more human-friendly to see the entity name.

Let me know if you would like me to raise a PR for this if you think it would be useful for others.

**Comment by tangollama** [comment]
@StephenGoodall, I personally agree with this enhancement and would like to take you up on an offer to PR the project. @Kav91, do you agree?

**Comment by StephenGoodall** [comment]
@tangollama I just realised I'm on an old version (not sure how as I only cloned it last week - maybe the nr1 nerdpack clone command is looking for the old version) but I've made the relevant changes based on the current master branch instead
The changes are the same for the tag 0.1.2 version, which is what nr1 clone pulled down for me. Let me know if I should make the changes on a different branch or anything.

**Comment by Kav91** [comment]
@StephenGoodall @tangollama yep this looks good to me, it also made me realize that I have a pointless ternary in there!

I'll merge the PR, then do a follow up commit to bump the version and remove that.
