### ISSUE TITLE
Include CPU and Memory values of Suggested Instance in Optimisation Candidates

### ISSUE THREAD

**Issue by StephenGoodall** [newrelic/nr1-cloud-optimize#30]
Currently, the optimisation candidate view shows the suggestedInstanceType, and clicking to see alternatives shows the CPU/Memory of those, but I can't see the CPU/Memory of the suggested type.

## Summary

I'd like to ad 2 columns to the Optimisation Candidates view to show the CPU/Memory of the suggested instance type.

## Desired Behaviour

See the CPU/Memory of the suggested Instance Type in the next two columns.

## Possible Solution

Will add a PR for this. Alternatively, maybe the suggested instance could be included in the "alternative" modal as that view shows the CPU/Memory for the alternatives

**Comment by Kav91** [comment]
I want to add this, just temporarily parking this as I'm about to make a large refactor in the coming weeks.

**Comment by Kav91** [comment]
Closing per comment in PR.
