### ISSUE TITLE
Tracking: refactor nerdlets/cloud-optimize-apm/components/optimization-candidates.js

### ISSUE THREAD

**Issue by tangollama** [newrelic/nr1-cloud-optimize#38]
nerdlets/cloud-optimize-apm/components/optimization-candidates.js is currently using a  deprecated lifecycle method, `componentWillReceiveProps`. The solution is likely related to more of a declarative model for rendering. This issue is here for tracking.

**Comment by Kav91** [comment]
Resolved in 2.0.0 release.
