### ISSUE TITLE
Unable to update the advanced config fields

### ISSUE THREAD

**Issue by rjusselrelic** [newrelic/nr1-cloud-optimize#41]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Unable to adjust the configuration fields 
 When trying to adjust these fields, the input is not received.  The field does not change, and the console shows the following message:
`[Violation] 'input' handler took 243ms`

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
Run the nerdpack, select the configuration menu option, and attempt to change a field value
[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour
The fields would show the changed value and upon exit/save update the multiplier, inclusion period etc.  

<img width="579" alt="Screen Shot 2020-04-30 at 11 32 29 PM" src="https://user-images.githubusercontent.com/20195081/80782424-c7d24900-8b3b-11ea-8541-10b94113e8a5.png">

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output
```
[Violation] 'input' handler took 198ms
[Violation] 'input' handler took 194ms
[Violation] 'input' handler took 187ms
[Violation] 'input' handler took 195ms
[Violation] 'input' handler took 217ms
[Violation] 'input' handler took 186ms
[Violation] 'input' handler took 186ms
[Violation] 'input' handler took 184ms
[Violation] 'input' handler took 241ms
[Violation] 'input' handler took 221ms
[Violation] 'input' handler took 216ms
[Violation] 'input' handler took 253ms
[Violation] 'input' handler took 230ms
[Violation] 'input' handler took 244ms
[Violation] 'input' handler took 244ms
[Violation] 'input' handler took 260ms
[Violation] 'input' handler took 243ms
[Violation] 'input' handler took 248ms
[Violation] 'input' handler took 235ms
[Violation] 'input' handler took 234ms
[Violation] 'input' handler took 254ms
[Violation] 'input' handler took 238ms
```
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
$ nr1 --version
@datanerd/nr1/1.22.2 darwin-x64 node-v10.16.3

* Browser name and version: 
   Chrome Version 81.0.4044.122 (Official Build) (64-bit) 
   Firefox 75.0 (64-bit)
* Operating System and version:
MacOS Catalina

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by Kav91** [comment]
@rjusselrelic thanks for raising. 

Just debugged the issue, it has broke on this PR https://github.com/newrelic/nr1-cloud-optimize/pull/40

cc @tangollama @devfreddy @danielgolden
