### ISSUE TITLE
Regardless of cloud provider, AWS instance types are suggested

### ISSUE THREAD

**Issue by crshanks** [newrelic/nr1-cloud-optimize#55]
When deployed from the NR App Catalog, the default cloud used for instance right size suggestions is not configurable. It is currently (2.1.0) set to "amazon"  in the code.

## Description

If the cloud provider is, say Azure, the suggested instance types are not Azure types, instead AWS types are provided:
![image](https://user-images.githubusercontent.com/44571906/87696315-88a1b480-c788-11ea-8aab-e6d0fb241e1c.png)

Deploying manually allows the value to be set in the code: nerdlets/cloud-optimize-core/context/data.js, by changing the optimizationDefaults.defaultCloud string from 'amazon' to your cloud provider, e.g. 'azure'.

## Steps to Reproduce

Deploy the nr1-cloud-optimize NR One application through the app catalog for an account where the hosts are in the Azure cloud.

## Expected Behaviour

Azure right-size suggestions provided, when the original instances are also Azure instances.

## Your Environment

NR1 CLI v1.22.2
Chrome v83
MacOS Catalina v10.15.5
Cloud Optimize release 2.1.0

## Additional Context

The suggested types could be based on:
- a single config option, through the UI
- the most common cloud instance type
- the existing instance cloud type: AWS instance > AWS instance, Azure instance > Azure instance

**Comment by Kav91** [comment]
@crshanks good catch, some of this code was ported from nimbus where you would set your desired cloud to migrate too at the beginning of the process.
This was an oversight, I'll put priority on this to rework this behaviour.

**Comment by Kav91** [comment]
Fixed in #b7eaf78.
Will send a PR to update the app catalog version.
