### ISSUE TITLE
Export optimization candidates to CSV

### ISSUE THREAD

**Issue by crshanks** [newrelic/nr1-cloud-optimize#56]
## Allow export to CSV

In earlier releases of the application it was possible to export the optimization candidates to CSV. This was a useful feature that I would like to see reinstated.

## Desired Behaviour

Reinstate the export to CSV button that allowed the current list of optimization candidates and their data to be exported.
![image](https://user-images.githubusercontent.com/44571906/88534048-2e61e880-cfff-11ea-9f9a-b53e638f43a8.png)

## Additional context

It was present in v1.1.0.

**Comment by Kav91** [comment]
Thanks, feature merged into master now, will do a catalog release shortly.
