### ISSUE TITLE
Add discount multiplier configuration setting

### ISSUE THREAD

**Issue by iamfuzz** [newrelic/nr1-cloud-optimize#61]
## Add discount multiplier configuration setting

It seems the ability to set a discount multiplier has been removed

## Desired Behaviour

Ideally, the customer would be able to provide their own RI setup/Savings Plan info (on the AWS side of things at least), but in the meantime, adding back the discount multiplier at least allows the user to tweak the numbers they see to match what they are actually paying.

## Additional context

This was available back in May and prior

**Comment by Kav91** [comment]
Given the in-app messaging in the #106 V3 release is for price guidance/best effort vs anything that should be considered as exact will close this as its unlikely to be implemented unless there is substantial feedback/requests for it, which we have not seen since.
