### ISSUE TITLE
Show Name tag from AWS instead of hostname

### ISSUE THREAD

**Issue by iamfuzz** [newrelic/nr1-cloud-optimize#62]
## Show Name tag instead of hostname

One of the default tags AWS (and I assume other cloud providers as well) provides for an instance is Name;  it is also one of the tags commonly used by customers when following tagging best practices to categorize and later more easily identify their instances.  Currently, Cloud Optimize only shows the hostname of an instance rather than its name, if available.

## Desired Behaviour

if instance.Name != None:
  name = instance.Name
else:
  name = hostname

## Additional context

I understand a multi-cloud approach has been taken which limits the ability to use certain cloud-specific data like this, but for this particular use case, I think it is important enough to implement.

**Comment by Kav91** [comment]
Closing, due to #106 being a complete re-write.
