### ISSUE TITLE
Add the ability to sort by cloud provider

### ISSUE THREAD

**Issue by iamfuzz** [newrelic/nr1-cloud-optimize#64]
## Summary

You can currently group my providerAccountName, but as an added step, it would be helpful if you could then sort and/ or filter by provider.

## Desired Behaviour

The ability to sort and filter by provider so that all AWS, GCP, and Azure accounts are grouped next to each other in alphabetical order, or filtered so that only accounts for one particular cloud provider are shown.

## Additional context

Some of our larger customers have a large number of cloud accounts under a single New Relic account;  many of them are only responsible for one cloud provider and would like the ability to sort and/or filter based on that one cloud provider.

**Comment by Kav91** [comment]
Group by `cloud` has always been available.
Closing.
