### ISSUE TITLE
Cache host data for quicker reload

### ISSUE THREAD

**Issue by iamfuzz** [newrelic/nr1-cloud-optimize#68]
## Summary

Users often click the back button or in some other way navigate out of Cloud Optimize, and in a large environment, it can take minutes for it to reload all of the host data.

## Desired Behaviour

Host data is cached for X number of minutes/hours with a button in the UI to clear the cache

## Possible Solution

Browser side caching

**Comment by Kav91** [comment]
Resolved in #106 , complete re-write that offloads processing and stores historical results as well.
