### ISSUE TITLE
Please Add Requirements for Node.js

### ISSUE THREAD

**Issue by lchapman4** [newrelic/nr1-cloud-optimize#70]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Summary
Supported node.js versions needed in the readme

## Desired Behaviour
Can someone add a blurb in the readme for the node.js requirement?  Currently it requires node versions 10 or 12 (v8 doesn't work), but it's not stated in the Getting Started section of the readme.  It should also come with a link to some site, nodejs.org or something similar, to show them how for their particular platform.

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Kav91** [comment]
This is not a Cloud Optimize or documentation issue.
Nobody should be developing with unsupported versions of NodeJS.

NodeJS v8 is no longer supported, and even v10 is in maintenance and will be EOL'd 2021-04-30.
https://nodejs.org/en/about/releases/


Closing.
