### ISSUE TITLE
AWS Windows EC2 instance Price Calculation

### ISSUE THREAD

**Issue by erkinkucuk** [newrelic/nr1-cloud-optimize#73]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

AWS Windows EC2 instance price calculation bug

## Description

Observed for EC2 Windows R5.Large instance. It is highly possible that it is a common issue. AWS EC2 instance price depends also on the OS. It looks like cloud optimize calculates windows instance price as if it is a linux instance. 

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version:
* Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by Kav91** [comment]
Closing, as the refactor has changed a lot of how calculations and instances are determined. We can reopen if the issue persists in the #106 V3 release.
