### ISSUE TITLE
Make pricing endpoint configurable & support for custom price lists

### ISSUE THREAD

**Issue by Kav91** [newrelic/nr1-cloud-optimize#8]
Should have a config var for the s3 bucket, so folks can store it themselves or point at their own instance of it when deploying to a new NR account. Is this small enough to store in NerdStore instead?

_Originally posted by @jthurman42 in https://github.com/newrelic/nr1-cloud-optimize/pull/7_

**Comment by tangollama** [comment]
@Kav91 can we close this one based on the PR referenced above?

**Comment by Kav91** [comment]
@tangollama I still wanted to make this customizable if the customer comes with their own price list, but I have not had much demand for it. So I think its fair to close it for now, and revisit it later if it does come up again.
