### ISSUE TITLE
Unable to save Configuration

### ISSUE THREAD

**Issue by dralph3344** [newrelic/nr1-cloud-optimize#87]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description:

Unable to save a configuration change for all entities, as well as Workload, with the Catalog Cloud Optimize.

## Steps to Reproduce

Change any element in the Configuration page (universal setting, or for a specific workload). Then select save. The save button then just spins and spins, never completing a save. Upon refresh, no values change.

## Expected Behaviour

Upon save, configuration would be retained and new executions of Optimize would reflect the new config change.

## Additional context

Please feel free to reach out to me asap with additional questions.

**Comment by jpvajda** [comment]
I was unable to reproduce this and could indeed save a change on the `Optimization Configs` page. @dralph3344 can you check this again and let us know if you still see an issue?

**Comment by dralph3344** [comment]
Hey @jpvajda, Thanks for looking at this. There are some capabilities around adjusting the configuration that we should investigate to make it a little easier.

That being said, Im actually good on this issue and was able to adjust the configuration. Thanks!
