### ISSUE TITLE
EC2 Instance Type Reporting Issue

### ISSUE THREAD

**Issue by ericnoelke** [newrelic/nr1-cloud-optimize#92]
The current instance type reported in Cloud Optimize does not match the current instance type in the AWS console. For example, Cloud Optimize is reporting the current instance type as r4.2xlarge when the EC2 console says it is r4.8xlarge. The r4.8xlarge has been running for several days so it should have reported in and been captured that the instance is no longer an r4.2xlarge.

**Comment by Kav91** [comment]
Hi, thanks for raising are you able to provide me some additional information on this instance please.

1. click query your data in top right
2. use the following query `SELECT * FROM SystemSample LIMIT 1 WHERE entityName = 'nameOfYourInstanceHERE'`
3. click the dropdown and select the json option
4. paste the json in your reply

**Comment by Kav91** [comment]
Closing, as potentially fixed in #106 release.
Reopen if issue persists.
