### ISSUE TITLE
Apply Time Picker for refreshing the Charts

### ISSUE THREAD

**Issue by GaneshR6** [newrelic/nr1-cloud-optimize#95]
[NOTE]: # Time Picker syncing and better Filters

## Sync the Charts to be refreshed based on NR1 time picker, Filterable Host/App/Tags instead of search queries.

[NOTE]: # Refresh charts based on Time picker selection, Ability to filter based on drop downs

## Refresh the Optimisation charts based on NR1 time picker, Ability to filter based on drop downs instead of Queries that need to be validated.

[NOTE]: # Refresh the Optimisation charts based on NR1 time picker, Ability to filter based on drop downs instead of Queries that need to be validated.
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Kav91** [comment]
Closing as #106 is a complete rewrite and the views are different now.
