### ISSUE TITLE
Include AWS Load balancers and EBS

### ISSUE THREAD

**Issue by GaneshR6** [newrelic/nr1-cloud-optimize#96]
[NOTE]: # Optmisation for unused Load balancer and unattached EBS volumes

## Provide cost impact of unused Load balancer and unattached EBS volumes

[NOTE]: # Provide $ figures against Load balancers and EBS volumes that are unused

## Filter list to choose what qualifies as Unused Load balancer and unattached  EBS volumes similar to EC2 today.

[NOTE]: # Provide the ability to calculate the costs for unused LBs and unattached EBS volumes

[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Possible Solution

[NOTE]: # ( Not required. Suggest how to implement the addition or change. )

## Additional context

[TIP]:  # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by Kav91** [comment]
Resolved ELB and ALB'S  in #106.
EBS potentially later.
